define([], function() {
  return {
    "PropertyPaneDescription": "Configure the Event Calendar web part",
    "DataSourceGroupName": "Data Source",
    "ListPickerLabel": "Select a list",
    "ColumnMappingGroupName": "Column Mapping",
    "TitleFieldLabel": "Title column",
    "StartDateFieldLabel": "Start date column",
    "EndDateFieldLabel": "End date column",
    "AllDayFieldLabel": "All day column (optional)",
    "CategoryFieldLabel": "Category column (optional)",
    "LocationFieldLabel": "Location column (optional)",
    "FieldsGroupName": "Additional Fields",
    "DisplaySettingsDescription": "Configure display and layout settings",
    "ViewSettingsGroupName": "View Settings",
    "ViewModeLabel": "Available Views",
    "DefaultViewLabel": "Default View",
    "CalendarViewTypeLabel": "Calendar View",
    "ListLayoutLabel": "List Layout",
    "MaxEventsLabel": "Maximum Events",
    "CardDisplayGroupName": "Card Display",
    "ShowCategoryLabel": "Show category",
    "ShowLocationLabel": "Show location",
    "ShowTimeLabel": "Show date and time",
    "ShowImageLabel": "Show image",
    "AppLocalEnvironmentSharePoint": "The app is running on your local environment as SharePoint web part",
    "AppLocalEnvironmentTeams": "The app is running on your local environment as Microsoft Teams app",
    "AppLocalEnvironmentOffice": "The app is running on your local environment in office.com",
    "AppLocalEnvironmentOutlook": "The app is running on your local environment in Outlook",
    "AppSharePointEnvironment": "The app is running on SharePoint page",
    "AppTeamsTabEnvironment": "The app is running in Microsoft Teams",
    "AppOfficeEnvironment": "The app is running in office.com",
    "AppOutlookEnvironment": "The app is running in Outlook",
    "UnknownEnvironment": "The app is running in an unknown environment"
  }
});
